export { default as Home } from "./Home";
export { default as About } from "./About";
export { default as Skills } from "./Skills";
export { default as Experience } from "./Experience";
export { default as Certificates } from "./Certificates";
export { default as Contact } from "./Contact";
export { default as NoFounds } from "./NoFounds";
export { default as LandingPage } from "./LandingPage";
export { default as LoadingPage } from "./Loadingpage";
